#!/bin/bash

set -e

echo -n 'Installing dependencies ... '

apt update > /dev/null 2>&1 && apt install -y git curl ruby > /dev/null 2>&1
chmod u+x ./ingress-nginx-tracing-repository/ci/scripts/extract_controller_image.rb

echo 'OK'

readonly RELEASE_TAG=$(cat ingress-nginx-releases/tag)
readonly RELEASE_COMMIT_SHA=$(cat ingress-nginx-releases/commit_sha)

echo -n "Retrieving container image for release ${RELEASE_TAG} (commit sha: ${RELEASE_COMMIT_SHA}) ... "

(cd ingress-nginx-repository && git checkout ${RELEASE_COMMIT_SHA} > /dev/null 2>&1)

readonly DEPLOYMENT_FILE='ingress-nginx-repository/deploy/static/provider/cloud/deploy.yaml'
readonly CONTROLLER_IMAGE=$(./ingress-nginx-tracing-repository/ci/scripts/extract_controller_image.rb < "${DEPLOYMENT_FILE}")

echo "${CONTROLLER_IMAGE}"

echo "Preparing the ${RELEASE_TAG} branch ..."

pushd ingress-nginx-tracing-repository
git checkout -b ${RELEASE_TAG}

# TODO Calculate these dynamically
libc_flavor='musl'
nginx_version='nginx/1.19.1'

echo "
[ingress-nginx-controller-${RELEASE_TAG}]
repo=https://github.com/kubernetes/ingress-nginx
tag=ingress-nginx-${RELEASE_TAG}
docker_image=${CONTROLLER_IMAGE}" >> build/init-container-config

git config --global 'user.email' 'stan@instana.com'
git config --global 'user.name' 'Stan'

git add build/init-container-config
git commit -m "Add build specification for ${RELEASE_TAG}"

readonly REMOTE_URL="$(git remote get-url origin)"

readonly REMOTE_WITH_AUTH="$(echo ${REMOTE_URL} | sed "s'://'&${GITHUB_TOKEN}@'g" )"

git push -f "${REMOTE_WITH_AUTH}" HEAD:refs/heads/${RELEASE_TAG}

popd

# TODO Create PR