apiVersion: v1
kind: Secret
metadata:
  name: instana-registry-key
data:
  .dockerconfigjson: <YOUR_BASE64_ENCODED_FILE_CONTENTS_HERE>
type: kubernetes.io/dockerconfigjson

# Ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
#
# This is just a template. Run command "docker login containers.instana.io"
# with username "_" and your Instana agent key as the password.
# Then run "cat ~/.docker/config.json | base64 --wrap=0" and put that into the
# line ".dockerconfigjson: ".
